### ISSUE TITLE
validate that the app works for selected example

### ISSUE THREAD

**Issue by apratap** [Sage-Bionetworks/shinyModules#5]
![screen shot 2016-06-29 at 10 45 01 am](https://cloud.githubusercontent.com/assets/146127/16462575/af9f2214-3de6-11e6-83ff-5d844d37a7d9.png)

**Comment by xindiguo** [comment]
Should drug/targetClass be filtered according to the selected samples? Your example did not work because HS01 and HS12 have no data related to NSC-75503 and GABRA1. The example below will work.

![screen shot 2016-07-05 at 1 34 21 pm](https://cloud.githubusercontent.com/assets/16565812/16598979/3fb44c6c-42b5-11e6-9774-ceea85bd4f2f.png)

**Comment by apratap** [comment]
Aah I see. Well in that case, I would think we shud make the code intelligent to atleast display that selected samples have no associated data for the selected target class. I think the most likely case is that there is no data for HS01 & HS12 samples.

**Comment by apratap** [comment]
discussed in-person w/Cindy : bug understood

**Comment by xindiguo** [comment]
Bug fixed. Works for both examples above.

**Comment by apratap** [comment]
Thank you :)
